name = "DensityInterfaceAD"
uuid = "8c3e8a3b-f22b-4810-a84a-f5557b07ad87"
authors = ["Philipp Gabler <phipsgabler@users.noreply.github.com>"]
version = "0.1.0"

[deps]
DensityInterface = "b429d917-457f-4dbc-8f4c-0cc954292b1d"
LogDensityProblems = "6fdf6af0-433a-55f7-b3ed-c6c6e0b8df7c"
